let Table = require('./jsql');
let table = new Table('price.csv', 'Price Indeces');
// table.printSchema();
// table.printTable();
// let result = table.simpleSearch('Ping', 49);
// let resultWithAttribute = table.simpleSearchWithAttribute('Date', '2017-11-16', 'ID');
// console.log(result);
// console.log(resultWithAttribute);
// table.printTable();
// table.printSchema();
// console.log(table.toString());
// console.dir(table.simpleSearch('Song', 'Dazed and Confused'));
// table.insert(table.table[1]);
// table.insert(table.table[2]);
// console.dir(table.simpleSearch('Song', 'Babe I\'m Gonna Leave You'));
// console.dir(table.duplicateSearch());
// table.toCSV();
table.toHTML();
// table.printTable();